//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace landSelling.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class administration
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public int phone { get; set; }
        public string address { get; set; }
    
        public virtual user user { get; set; }
    }
}
